#!/bin/bash
set -euo pipefail

source=$(ct-filelist --filter=source --style Flat "$1"|tr '\n' ' ')
ct-create-makefile -vvvv --dynamic "$1" $source

cpu_count=$(cat /proc/cpuinfo |grep processor | wc -l)
make -j$((2*cpu_count))

# These are the headers that have to be included
#headers=$(ct-headertree --style Flat "$1" | tr '\n' ' ')
