#!/bin/bash
set -euo pipefail

cmd='ct-cake '
# TODO: compile c source too. don't look in bindir, objdir for source files
all_exe_sources=$(find . -name '*.cpp' -or -name '*.c' |xargs grep -l main\( | tr '\n' ' ')
cmd+=$all_exe_sources

test_dirs=$(find . -maxdepth 1 -type d -name 'test*' | tr '\n' ' ')
all_test_sources=""
for test_dir in $test_dirs; do
    all_test_sources+=$(find "$test_dir" -name 'test*cpp' | tr '\n' ' ')
done

if [[ $all_test_sources ]]; then
    cmd+=" --tests ${all_test_sources}"
fi

cmd+=" $@"

echo $cmd
eval $cmd

cpu_count=$(cat /proc/cpuinfo |grep processor | wc -l)
make -j$((2*cpu_count)) -f Makefile.*



