#!/bin/bash
set -euo pipefail

startsource=$1
shift
source=$(ct-filelist --filter=source --style flat "$startsource"|tr '\n' ' ')
ct-create-makefile --dynamic "$startsource" ${source} "$@"

make -j$(ct-jobs)

# These are the headers that have to be included
#headers=$(ct-headertree --style Flat "$1" | tr '\n' ' ')
