#!/bin/bash

# TODO: compile c source too. don't look in bindir, objdir for source files
all_exes=$(find . -name '*.cpp' |xargs grep -l main\( | tr '\n' ' ')
ct-create-makefile $all_exes "$@"

cpu_count=$(cat /proc/cpuinfo |grep processor | wc -l)
make -j$((2*cpu_count))
