#!/bin/bash
set -euo pipefail

startsource=$1
shift
source=$(ct-filelist --filter=Source --style Flat "$startsource"|tr '\n' ' ')
ct-create-makefile --static "$startsource" ${source} "$@"

cpu_count=$(cat /proc/cpuinfo |grep processor | wc -l)
make -j$((2*cpu_count)) -f Makefile*

# These are the headers that have to be included
#headers=$(ct-headertree --style Flat "$1" | tr '\n' ' ')
