#!/bin/bash
set -euo pipefail

all=$(ct-findtargets --style=args $@)
cmd="ct-create-makefile ${all} $@"
echo $cmd
eval $cmd

cpu_count=$(cat /proc/cpuinfo |grep processor | wc -l)
make -j$((2*cpu_count)) 



