#! /usr/bin/env python
from __future__ import print_function
from __future__ import unicode_literals

import os
import argparse
import ct.dirnamer

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Determine the currently used ct cache')
    parser.add_argument(
        "-v",
        "--verbose",
        help="Output verbosity. Add more v's to make it more verbose",
        action="count",
        default=0)
    args = parser.parse_args() 

    try:            
        cachedir = os.environ['CTCACHE']
        if cachedir == 'None':
            if args.verbose > 0:
                print("Environment variable CTCACHE is None.  Disk caching is disabled.")
        else:
            if args.verbose > 0:
                print("".join(["Environment variable CTCACHE is ", cachedir, ". Using this as the cache directory."]))

    except KeyError:
        if args.verbose > 0:
            print("Environment variable CTCACHE doesn't exist.  Falling back to python-appdirs (which on linux wraps XDG variables)")
        cachedir = ct.dirnamer.user_cache_dir()

    print(cachedir)
