#!/usr/bin/env python
from __future__ import print_function
import configargparse
import utils
from hunter import HeaderDependencies

if __name__ == '__main__':
    cap = configargparse.getArgumentParser(
        description='Determine header dependencies of a C/C++ file by invoking $CPP -MM <filename>. ',
        formatter_class=configargparse.DefaultsRawFormatter)
    cap.add("filename", help="File to use in \"$CPP $CPPFLAGS -MM filename\"")
    cap.add("-c", "--config", is_config_file=True, help="config file path")
    hh = HeaderDependencies()
    myargs = cap.parse_known_args()
    utils.verbose_print_args(myargs[0])

    for dep in hh.process(myargs[0].filename):
        print(dep)
