#! /usr/bin/env python
from __future__ import unicode_literals
from __future__ import print_function
import shutil
import appdirs
""" Remove the cache used by the ct-* programs. """

def main():
    cachedir = appdirs.user_cache_dir(appname='ct')
    shutil.rmtree(cachedir)

if __name__ == '__main__':
    main()
