#! /usr/bin/env python
from __future__ import print_function
from __future__ import unicode_literals

import shutil
import ct.dirnamer

""" Remove the cache used by the ct-* programs. """


def main():
    cachedir = ct.dirnamer.user_cache_dir(appname='ct')
    shutil.rmtree(cachedir)


if __name__ == '__main__':
    main()
