#!/usr/bin/env python
from __future__ import print_function
import configargparse
from headerhunter import HeaderDependencies

if __name__ == '__main__':
    cap = configargparse.getArgumentParser(
        description='Determine header dependencies of a C/C++ file by invoking $CPP -MM <filename>. ',
        formatter_class=configargparse.DefaultsRawFormatter)
    cap.add("filename", help="File to use in \"$CPP $CPPFLAGS -MM filename\"")
    cap.add("-c", "--config", is_config_file=True, help="config file path")
    hh = HeaderDependencies()
    myargs = cap.parse_known_args()

    if myargs[0].verbose >= 1:
        print(myargs[0])
    if myargs[0].verbose >= 2:
        cap.print_values()

    for dep in hh.process(myargs[0].filename):
        print(dep)
