#! /usr/bin/env python
from __future__ import print_function
from __future__ import unicode_literals

import os
import argparse
import ct.dirnamer

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Determine the currently used ct cache')
    ct.dirnamer.add_arguments(parser)
    parser.add_argument(
        "-v",
        "--verbose",
        help="Output verbosity. Add more v's to make it more verbose",
        action="count",
        default=0)
    args = parser.parse_args() 
    print(ct.dirnamer.user_cache_dir(args=args))
