#! /usr/bin/python3
import configargparse
import sys
import ct.dirnamer

if __name__ == "__main__":
    variant = ct.configutils.extract_variant()
    config_files = ct.configutils.config_files_from_variant()
    cap = configargparse.getArgumentParser(
        description="Determine the currently used ct cache",
        formatter_class=configargparse.ArgumentDefaultsHelpFormatter,
        auto_env_var_prefix="",
        default_config_files=config_files,
        args_for_setting_config_path=["-c", "--config"],
        ignore_unknown_config_file_keys=True,
    )

    sys.exit(ct.dirnamer.main())
