#! /usr/bin/env python
import sys

import configargparse
import ct.utils
import ct.findtargets


if __name__ == '__main__':
    variant = ct.configutils.extract_variant()
    config_files = ct.configutils.config_files_from_variant()
    cap = configargparse.getArgumentParser(
        description='Find the source files that are executable targets and tests',
        formatter_class=configargparse.ArgumentDefaultsHelpFormatter,
        default_config_files=config_files,
        args_for_setting_config_path=["-c","--config"],
        ignore_unknown_config_file_keys=True)
    sys.exit(ct.findtargets.main())
