#!/usr/bin/env python3
import sys
import configargparse
import compiletools.utils
import compiletools.filelist

if __name__ == "__main__":
    config_files = compiletools.configutils.config_files_from_variant()
    cap = configargparse.getArgumentParser(
        description="Determine header and source dependencies of a C/C++ file by following headers and implied source files.",
        formatter_class=configargparse.ArgumentDefaultsHelpFormatter,
        auto_env_var_prefix="",
        default_config_files=config_files,
        args_for_setting_config_path=["-c", "--config"],
        ignore_unknown_config_file_keys=True,
    )
    sys.exit(compiletools.filelist.main())
