#!/usr/bin/python3
import sys
import configargparse
import ct.apptools
import ct.git_utils

if __name__ == "__main__":
    cap = configargparse.getArgumentParser(
        description="Determine the path of the git root.",
        formatter_class=configargparse.ArgumentDefaultsHelpFormatter,
        auto_env_var_prefix="",
    )
    sys.exit(ct.git_utils.main())
