#! /usr/bin/env python
import sys

import configargparse
import ct.utils
import ct.magicflags


if __name__ == '__main__':
    variant = ct.utils.extract_variant_from_argv()
    config_files = ct.utils.config_files_from_variant()
    cap = configargparse.getArgumentParser(
        description='Parse a file and show the magicflags it exports',
        formatter_class=configargparse.DefaultsRawFormatter,
        default_config_files=config_files)

    # The config file has to be added here.  For some reason doing it in the
    # ct.utils.add_common_arguments, or elsewhere, fails.
    cap.add(
        "-c",
        "--config",
        is_config_file=True,
        help="Manually specify the config file path if you want to override the variant default")

    sys.exit(ct.magicflags.main())
