#!/usr/bin/env python
from __future__ import print_function
from headerhunter import HeaderTree
import tree
import configargparse

from pprint import pprint

if __name__ == '__main__':
    cap = configargparse.getArgumentParser()
    cap.add("filename", help="File to use in \"$CPP $CPPFLAGS -MM filename\"")
    cap.add("-c", "--config", is_config_file=True, help="config file path")
    ht = HeaderTree()

    myargs = cap.parse_known_args()

    if myargs[0].verbose >= 1:
        print(myargs[0])
    if myargs[0].verbose >= 2:
        cap.print_values()

    inctree = ht.process(myargs[0].filename)
    pprint(tree.dicts(inctree))
