#!/usr/bin/env python
from __future__ import print_function
from headerhunter import HeaderTree
import utils
import git_utils
import tree
import configargparse

from pprint import pprint


def print_wrapper(data):
    """ Wrap the builtin print so that it can be passed to the tree.depth_first_traverse """
    print(data)


def depth_indicator_print(key, depth, indicator='--', strip_git_root=True):
    """ Print the filenames with a leading indicator to denote the depth of the file from the root """
    name = key
    if strip_git_root:
        name = git_utils.strip_git_root(key)
    print(indicator * depth + name)


class DotFormat:

    """ Print the include tree in graphviz dot format. """

    def __init__(self, tree_, strip_git_root=True):
        self.strip_git_root = strip_git_root
        for key in tree_:
            # TODO: Take care of the case where there are multiple top level
            # nodes
            if strip_git_root:
                self.name = git_utils.strip_git_root(key)
            else:
                self.name = key
        self._print_header()
        tree.depth_first_traverse(
            tree=tree_,
            pre_traverse_function=self._print_node)
        self._print_footer()

    def _print_header(self):
        print('digraph "' + self.name + '" {')

    def _print_footer(self):
        print("}")

    def _print_node(self, key, value):
        name = key
        if self.strip_git_root:
            name = git_utils.strip_git_root(key)
        print('"' + name + '"')

        for child_key in value:
            child_name = child_key
            if self.strip_git_root:
                child_name = git_utils.strip_git_root(child_key)
            print('"' + name + '"->"' + child_name + '"')


class CostCounter:

    """ Show the cumulative cost and self cost of including the header files """

    def __init__(self, tree_, indicator='--', strip_git_root=True):
        self.indicator = indicator
        self.strip_git_root = strip_git_root
        self.counter = [0]
        tree.depth_first_traverse(
            tree=tree_,
            pre_traverse_function=self._pre,
            post_traverse_function=self._post)

    def _pre(self, key, value, depth):
        self.counter.append(0)

    def _post(self, key, value, depth):
        last = self.counter.pop()
        self.counter[-1] += last + 1
        name = key
        if self.strip_git_root:
            name = git_utils.strip_git_root(key)
        # print cumulative includes and direct includes
        print(
            "{c:5d}".format(
                c=last) +
            "{d:3d}".format(
                d=len(value)) +
            " " +
            self.indicator *
            depth +
            name)


if __name__ == '__main__':
    cap = configargparse.getArgumentParser()
    cap.add("filename", help="File to start tracing headers from")
    cap.add("-c", "--config", is_config_file=True, help="config file path")
    ht = HeaderTree()

    myargs = cap.parse_known_args()

    if myargs[0].verbose >= 1:
        print(myargs[0])
    if myargs[0].verbose >= 2:
        cap.print_values()

    inctree = ht.process(myargs[0].filename)
#    tree.depth_first_traverse(tree=inctree,post_traverse_function=print_wrapper)
#    tree.depth_first_traverse(tree=inctree,pre_traverse_function=depth_indicator_print)
#    pprint(tree.dicts(inctree))

#    df = DotFormat(inctree)
#    print()

    cc = CostCounter(inctree)
    print()
